export const PERMISSIONS: Array<{ code: string; name: string; category: string }> = [
  { code: 'dashboard:admin', name: 'View admin dashboard', category: 'Dashboard' },
  { code: 'dashboard:worker', name: 'View worker dashboard', category: 'Dashboard' },
  { code: 'users:manage', name: 'Create and manage workers', category: 'Workers' },
  { code: 'customers:read_all', name: 'View all customers', category: 'Customers' },
  { code: 'customers:read_own', name: 'View assigned customers', category: 'Customers' },
  { code: 'customers:manage', name: 'Create and edit customers', category: 'Customers' },
  { code: 'customers:merge', name: 'Merge duplicate customers', category: 'Customers' },
  { code: 'leads:read_all', name: 'View all leads', category: 'Leads' },
  { code: 'leads:read_own', name: 'View assigned leads', category: 'Leads' },
  { code: 'leads:create', name: 'Create leads', category: 'Leads' },
  { code: 'leads:update', name: 'Edit any lead', category: 'Leads' },
  { code: 'leads:update_own', name: 'Edit assigned leads', category: 'Leads' },
  { code: 'leads:assign', name: 'Assign and reassign leads', category: 'Leads' },
  { code: 'follow_ups:read_all', name: 'View all follow-ups', category: 'Follow-ups' },
  { code: 'follow_ups:read_own', name: 'View own follow-ups', category: 'Follow-ups' },
  { code: 'follow_ups:create', name: 'Create follow-ups', category: 'Follow-ups' },
  { code: 'follow_ups:update', name: 'Update any follow-up', category: 'Follow-ups' },
  { code: 'follow_ups:update_own', name: 'Update assigned follow-ups', category: 'Follow-ups' },
  { code: 'notes:create', name: 'Add lead notes', category: 'Leads' },
  { code: 'calls:read_all', name: 'View all calls', category: 'Calling' },
  { code: 'calls:read_own', name: 'View own calls', category: 'Calling' },
  { code: 'calls:create', name: 'Log and place calls', category: 'Calling' },
  { code: 'calls:update', name: 'Edit any call', category: 'Calling' },
  { code: 'calls:update_own', name: 'Edit own calls', category: 'Calling' },
  { code: 'recordings:access', name: 'Play call recordings', category: 'Calling' },
  { code: 'quotations:read_all', name: 'View all quotations', category: 'Sales' },
  { code: 'quotations:read_own', name: 'View own quotations', category: 'Sales' },
  { code: 'quotations:create', name: 'Create quotations', category: 'Sales' },
  { code: 'quotations:update_own', name: 'Update own quotations', category: 'Sales' },
  { code: 'quotations:manage', name: 'Update any quotation', category: 'Sales' },
  { code: 'bookings:read_all', name: 'View all bookings', category: 'Sales' },
  { code: 'bookings:read_own', name: 'View own bookings', category: 'Sales' },
  { code: 'bookings:create', name: 'Create bookings', category: 'Sales' },
  { code: 'bookings:update_own', name: 'Update own bookings', category: 'Sales' },
  { code: 'bookings:manage', name: 'Update any booking', category: 'Sales' },
  { code: 'communications:read', name: 'View communications', category: 'Communication' },
  { code: 'communications:send', name: 'Send messages', category: 'Communication' },
  { code: 'documents:read', name: 'View documents', category: 'Documents' },
  { code: 'documents:upload', name: 'Upload documents', category: 'Documents' },
  { code: 'documents:manage', name: 'Delete documents', category: 'Documents' },
  { code: 'reports:read', name: 'Run reports', category: 'Reporting' },
  { code: 'exports:run', name: 'Export CRM data', category: 'Reporting' },
  { code: 'imports:manage', name: 'Import leads', category: 'Reporting' },
  { code: 'analytics:read', name: 'View worker performance', category: 'Reporting' },
  { code: 'automation:manage', name: 'Manage assignment and reminder automation', category: 'Automation' },
  { code: 'ai:use', name: 'Use AI assistance', category: 'Automation' },
  { code: 'settings:manage', name: 'Manage CRM settings', category: 'Settings' },
  { code: 'audit:read', name: 'View audit logs', category: 'Settings' },
];

export const ALL_PERMISSION_CODES = PERMISSIONS.map((p) => p.code);

export const ROLE_PERMISSIONS: Record<string, string[]> = {
  ADMIN: ALL_PERMISSION_CODES,
  WORKER: [
    'dashboard:worker',
    'customers:read_own',
    'leads:read_own',
    'leads:update_own',
    'follow_ups:read_own',
    'follow_ups:create',
    'follow_ups:update_own',
    'notes:create',
    'calls:read_own',
    'calls:create',
    'calls:update_own',
    'recordings:access',
    'quotations:read_own',
    'quotations:create',
    'quotations:update_own',
    'bookings:read_own',
    'bookings:create',
    'bookings:update_own',
    'communications:read',
    'communications:send',
    'documents:read',
    'documents:upload',
    'ai:use',
  ],
};

export const ROLES = [
  { code: 'ADMIN', name: 'Admin / Owner', description: 'Full access to the CRM' },
  { code: 'WORKER', name: 'Worker / Employee', description: 'Access limited to assigned work' },
];

export type PermissionCode = (typeof ALL_PERMISSION_CODES)[number];
